# Site settings
site: Ephesus
title: VuNguyen's SRE Blog
keywords: ephesus, blog
description: >-
  Ephesus - Minimalist Jekyll Theme aaaaaaaaaaaaaaaaa
lang: en-US
timezone:  Asian/Ho_Chi_Minh
repo: https://github.com/onepase/Ephesus # site repo [optional]
google_verify:      XXX # Put your Google Verification here
google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
discus-identifier:  XXX

# Author settings
author:
  name: Vu Nguyen
  bio: Site Reliability Engineer @CocCoc <br> Open Source /#linux
  picture: assets/images/avatar.jpg 
  github: vuvietnguyenit # github username
  linkedin: vunguyen1407 # linkedin username
  email: vuviet.nguyen.docs@gmail.com # email adress


# URL settings
url: "https://vuvietnguyenit.github.io" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false